---

- name: Create nginx web root folder
  file: path=/var/html mode=0777 state=directory

- name: Configure nginx web root folder in Ubuntu
  when: ( ansible_distribution == "Ubuntu" )
  copy: src=default dest=/etc/nginx/sites-available/default
  notify:
      - Restart nginx web server

- name: Configure nginx web root folder in CentOS 
  when: ( ansible_distribution == "CentOS" )
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify:
      - Restart nginx web server

...
